config/routes.rb
Rails.application.routes.draw do
  resources :entries
  devise_for :officers

  root 'home#index'
  get '/blog' => 'home#blog'
    get '/getEntries' => 'entries#getEntries'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/models/officer.rb
class Officer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_officer!, only: [:index, :new, :edit, :update, :destroy]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries
  # GET /entries.json
  def getEntries
    @entries = Entry.all
    respond_to do |format|
     format.json {render json: @entries}
   end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:officer, :title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :officer %><br>
    <%= f.text_field :officer %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="container devise">
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>
</div>

app/views/entries/index.html.erb
<div class="devise container">
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Officer</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.officer %></td>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>
</div>

app/views/entries/new.html.erb
<div class="container devise">
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>
</div>

app/views/entries/show.html.erb
<div class="container devise">
<p id="notice"><%= notice %></p>

<p>
  <strong>Officer:</strong>
  <%= @entry.officer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>
</div>

app/views/home/index.html.erb
<html>
  <head>
    <title>UA Web Development Club</title>
  </head>
  <body>
      <div class ="header">
        <div class="container">
          <div class="welcome">
            <h1>&#60;UA Web Dev Club&#47;&#62;</h1>
            <p>
              Learn about how the web works all the way to creating your own web app!
              Club is open to anyone and all experience levels!
            </p>
        </div>
        </div>
      </div>


      <div class="content">
        <section id="about">
            <div class="container">
            <h2>About</h2>
            <p>
              The hope of this club is to help students learn about modern web dev and create their own web apps!
              This club aims to help students add skills to their repertoire and give them the chance to connect with professionals
              about industry web development.
              We welcome all majors and experience levels! We're here to learn together!
              <p>
                Topics that will be covered:
                <ul>
                  <li>How the Web Works</li>
                  <li>HTML/CSS</li>
                  <li>Web Frameworks: Ruby on Rails (MVC Architectural Pattern)</li>
                  <li>Bootstrap</li>
                  <li>Servers</li>
                  <li>JavaScript</li>
                  <li>jQuery</li>
                  <li>ReactJS</li>
                  <li>Databases: MySQL</li>
                  <li>Git</li>
                  <li>Heroku</li>
              </ul>

            </p>
          </div>
        </section>
        <section id="when">
          <div class="container">
            <h2>When/Where</h2>
            <p>
              Tuesdays at 6pm!
              Room is Gould-Simpson 701.
            </p>
          </div>
        </section>
        <section id="events">
          <div class="container">
            <h2>Events</h2>
            <p>
              TBD
            </p>
          </div>
        </section>
        <section id="news">
          <div class="container">
            <h2>News/Announcements</h2>
            <%= react_component('Blog') %>
          </div>
        </section>
        <section id="contact">
          <div class="container">
            <h2>Contact</h2>
            <div class="contactIcons">
              <a href="mailto:uawebdevclub@gmail.com"><i class="fa fa-envelope fa-3x" aria-hidden="true"></i></a>
              <a href="https://www.facebook.com/groups/572149922960422/"><i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></a>
            </div>
          </div>
        </section>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <title>UA Web Development Club</title>
  <!-- Normalize CSS -->
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">

  <!-- Latest icon font stylesheet-->
  <link rel="stylesheet" href="//brand.arizona.edu/sites/all/themes/brand/ua-brand-icons/ua-brand-icons.css">

  <!-- Latest compiled and minified CSS icon font not included-->
  <link rel="stylesheet" href="//bitbucket.org/uadigital/ua-bootstrap/downloads/ua-bootstrap-1.0.0-beta1.min.css">

  <!-- jQuery -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
              <div class="row">
                <div class="navbar-header">
                  <button type="button" data-toggle="collapse" data-target="#main-navbar" aria-expanded="false" aria-controls="navbar" class="navbar-toggle collapsed"><span class="sr-only">Toggle navigation</span>
                    <!-- span.icon-bar-->
                    <!-- span.icon-bar-->
                    <!-- span.icon-bar--><span class="text">MAIN MENU</span>
                  </button>
                </div>
                <div id="main-navbar" class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    <% if current_page?(root_path) %>
                      <li class="active"><a id ="home" class="page-scroll" href="#page-top">Home</a></li>
                    <% else %>
                      <li class="active"><%= link_to('Home', root_path)%></li>
                    <%end%>
                    <li class="false"><a class="page-scroll" href="#about">About</a></li>
                    <li class="false"><a class="page-scroll" href="#when">When/Where</a></li>
                    <li class="false"><a class="page-scroll" href="#events">Events/Schedule</a></li>
                    <li class="false"><a a class="page-scroll" href="#news" >News/Announcements</a></li>
                    <li class="false"><a class="page-scroll" href="#contact">Contact</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <% if officer_signed_in? %>
                      <li> <%= link_to('Blog Entries', entries_path)%></li>
                      <li>
                      <%= link_to('Logout', destroy_officer_session_path, :method => :delete) %>
                      </li>
                    <% else %>
                      <li>
                      <%= link_to('Officer Login', new_officer_session_path)  %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>
<%= yield %>

</body>
</html>